import { useState } from 'react';
import { useRouter } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';

import { AuthButton, authColors, authStyles } from '@/features/auth/auth-ui';
import { saveOnboardingValue } from '@/features/auth/onboarding';
import { useAuth } from '@/features/auth/auth-context';
import { Choice } from '@/features/auth/onboarding-ui';

export default function ActivityScreen() { const router = useRouter(); const { email } = useAuth(); const [activity, setActivity] = useState('Active'); const next = async () => { if (email) await saveOnboardingValue(email, 'activity', activity); router.push('/onboarding/dietary'); }; return <View style={[authStyles.screen, styles.screen]}><Progress /><Text style={styles.back} onPress={() => router.back()}>‹  Back</Text><Text style={styles.title}>What is your{`\n`}activity level?</Text><Text style={styles.subtitle}>This helps us calculate your daily calorie needs and health goals accurately.</Text><Choice title="Sedentary" detail="Office job, little to no exercise" selected={activity === 'Sedentary'} onPress={() => setActivity('Sedentary')} /><Choice title="Light" detail="1-2 days of light activity/week" selected={activity === 'Light'} onPress={() => setActivity('Light')} /><Choice title="Active" detail="3-5 days of exercise/week" selected={activity === 'Active'} onPress={() => setActivity('Active')} /><Choice title="Very Active" detail="Hard exercise 6-7 days/week" selected={activity === 'Very Active'} onPress={() => setActivity('Very Active')} /><View style={styles.bottom}><AuthButton title="Next  ›" onPress={next} /></View></View>; }
function Progress() { return <><View style={styles.progress}><Text style={styles.section}>ACTIVITY PROFILE</Text><Text style={styles.step}>70% Complete</Text></View><View style={styles.track}><View style={[styles.fill, { width: '70%' }]} /></View></>; }
const styles = StyleSheet.create({ screen: { padding: 24 }, progress: { flexDirection: 'row', justifyContent: 'space-between' }, section: { color: authColors.green, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, step: { color: '#91A4BF', fontSize: 11, fontWeight: '700' }, track: { backgroundColor: '#DDE5EF', height: 6, marginTop: 10 }, fill: { backgroundColor: authColors.green, height: '100%' }, back: { color: '#91A4BF', fontSize: 15, marginTop: 44 }, title: { color: authColors.navy, fontSize: 31, fontWeight: '900', lineHeight: 38, marginTop: 26 }, subtitle: { color: authColors.muted, fontSize: 16, lineHeight: 25, marginTop: 14 }, bottom: { marginTop: 'auto', paddingTop: 24 } });
