import { useState } from 'react';
import { useRouter } from 'expo-router';
import { StyleSheet, Text, TextInput, View } from 'react-native';

import { AuthButton, authColors, authStyles } from '@/features/auth/auth-ui';
import { saveOnboardingValue } from '@/features/auth/onboarding';
import { useAuth } from '@/features/auth/auth-context';

export default function AllergiesScreen() { const router = useRouter(); const { email } = useAuth(); const [allergy, setAllergy] = useState('Nuts'); const next = async () => { if (email) await saveOnboardingValue(email, 'allergy', allergy); router.push('/onboarding/activity'); }; return <View style={[authStyles.screen, styles.screen]}><Progress /><Text style={styles.back} onPress={() => router.back()}>‹  Back</Text><Text style={styles.title}>Any allergies or{`\n`}ingredients to avoid?</Text><Text style={styles.subtitle}>This helps us recommend safer meals and avoid ingredients that may affect your health.</Text><TextInput value={allergy} onChangeText={setAllergy} placeholder="⌕   Search" placeholderTextColor="#899AB2" style={styles.search} />{['Nuts', 'Dairy', 'Eggs', 'Seafood'].map((item) => <Text key={item} onPress={() => setAllergy(item)} style={[styles.allergy, allergy === item && styles.selected]}>{item}</Text>)}<View style={styles.bottom}><AuthButton title="Next  ›" onPress={next} /></View></View>; }
function Progress() { return <><View style={styles.progress}><Text style={styles.section}>PERSONAL DETAILS</Text><Text style={styles.step}>60% Complete</Text></View><View style={styles.track}><View style={[styles.fill, { width: '60%' }]} /></View></>; }
const styles = StyleSheet.create({ screen: { padding: 24 }, progress: { flexDirection: 'row', justifyContent: 'space-between' }, section: { color: authColors.green, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, step: { color: '#91A4BF', fontSize: 11, fontWeight: '700' }, track: { backgroundColor: '#DDE5EF', height: 6, marginTop: 10 }, fill: { backgroundColor: authColors.green, height: '100%' }, back: { color: '#91A4BF', fontSize: 15, marginTop: 44 }, title: { color: authColors.navy, fontSize: 31, fontWeight: '900', lineHeight: 38, marginTop: 26 }, subtitle: { color: authColors.muted, fontSize: 16, lineHeight: 25, marginTop: 14 }, search: { backgroundColor: '#FFF', borderRadius: 28, color: authColors.navy, fontSize: 17, marginTop: 34, padding: 20 }, allergy: { backgroundColor: '#FFF', borderRadius: 28, color: authColors.navy, fontSize: 18, fontWeight: '800', marginHorizontal: 10, marginTop: 12, padding: 18, textAlign: 'center', width: '43%' }, selected: { borderColor: authColors.green, borderWidth: 1 }, bottom: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 'auto', paddingTop: 20, width: '100%' } });
