import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { authColors, authStyles, AuthButton } from '@/features/auth/auth-ui';

export default function LanguageScreen() {
  const router = useRouter();
  const [language, setLanguage] = useState('English');
  return <View style={[authStyles.screen, styles.screen]}><View style={styles.progress}><Text style={styles.progressLabel}>INITIAL SETUP</Text><Text style={styles.step}>10% Complete</Text></View><View style={styles.track}><View style={styles.fill} /></View><Text style={styles.back} onPress={() => router.back()}>‹  Back</Text><Text style={styles.title}>Language &{`\n`}Region</Text><Text style={styles.subtitle}>Choose your preferred language for a better health management experience.</Text><Option title="🇺🇸   English" detail="System Default" selected={language === 'English'} onPress={() => setLanguage('English')} /><Option title="🇵🇭   Filipino / Tagalog" detail="Lokal na Wika" selected={language === 'Filipino'} onPress={() => setLanguage('Filipino')} /><View style={styles.info}><Text style={styles.infoIcon}>●</Text><Text style={styles.infoText}>You can change your language preferences at any time in the app settings.</Text></View><View style={styles.bottom}><AuthButton title="Next  ›" onPress={() => router.push('/onboarding/profile-type')} /><Text style={styles.hint}>◉    Content will adapt based on your selection.</Text></View></View>;
}

function Option({ title, detail, selected, onPress }: { title: string; detail: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.option, selected && styles.selected]}><View style={styles.optionText}><Text style={styles.optionTitle}>{title}</Text><Text style={styles.detail}>{detail}</Text></View><View style={[styles.radio, selected && styles.radioSelected]}>{selected ? <Text style={styles.check}>✓</Text> : null}</View></Pressable>; }

const styles = StyleSheet.create({ screen: { padding: 24 }, progress: { flexDirection: 'row', justifyContent: 'space-between' }, progressLabel: { color: authColors.green, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, step: { color: '#91A4BF', fontSize: 11, fontWeight: '700' }, track: { backgroundColor: '#DDE5EF', borderRadius: 4, height: 6, marginTop: 10 }, fill: { backgroundColor: authColors.green, borderRadius: 4, height: '100%', width: '10%' }, back: { color: '#91A4BF', fontSize: 15, marginTop: 44 }, title: { color: authColors.navy, fontSize: 32, fontWeight: '900', lineHeight: 38, marginTop: 26 }, subtitle: { color: authColors.muted, fontSize: 16, lineHeight: 25, marginTop: 14 }, option: { alignItems: 'center', backgroundColor: '#FFF', borderColor: '#FFF', borderRadius: 24, borderWidth: 2, flexDirection: 'row', justifyContent: 'space-between', marginTop: 18, minHeight: 86, paddingHorizontal: 20 }, selected: { borderColor: authColors.green }, optionText: { gap: 5 }, optionTitle: { color: authColors.navy, fontSize: 18, fontWeight: '800' }, detail: { color: '#91A4BF', fontSize: 14, marginLeft: 37 }, radio: { alignItems: 'center', borderColor: authColors.border, borderRadius: 14, borderWidth: 2, height: 24, justifyContent: 'center', width: 24 }, radioSelected: { backgroundColor: authColors.green, borderColor: authColors.green }, check: { color: '#FFF', fontWeight: '900' }, info: { alignItems: 'flex-start', backgroundColor: '#F0F7E7', borderRadius: 18, flexDirection: 'row', gap: 12, marginTop: 40, padding: 20 }, infoIcon: { color: authColors.green, fontSize: 16 }, infoText: { color: authColors.green, flex: 1, fontSize: 14, lineHeight: 23 }, bottom: { marginTop: 'auto', paddingTop: 34 }, hint: { color: '#91A4BF', fontSize: 12, marginTop: 24, textAlign: 'center' } });
