import { SuggestionScreen } from '@/features/ai/suggestion-screen';
import type { ExerciseSuggestion } from '@/features/ai/types';
import { requestExerciseSuggestions } from '@/lib/ai';

// Exercise Tips (Figma 195:1390). Generated by the Cloud Function like the meal suggestions.
export default function ExerciseTipsScreen() {
  return (
    <SuggestionScreen<ExerciseSuggestion>
      kind="exercise"
      title="Exercise Tips"
      subtitle="Activities that can support your daily diabetes management."
      request={requestExerciseSuggestions}
      card={(exercise) => ({ title: exercise.name, text: exercise.description })}
      buttonLabel="View Exercise"
      detailsPath="/exercise-details"
      icon={{ ios: 'figure.walk', android: 'directions_walk', web: 'directions_walk' }}
    />
  );
}
