import { SuggestionScreen } from '@/features/ai/suggestion-screen';
import type { MealSuggestion } from '@/features/ai/types';
import { requestMealSuggestions } from '@/lib/ai';

// Meal Suggestions (Figma 195:923). The meals are generated by the Cloud Function from the person's profile,
// allergies and latest reading; see features/ai/suggestion-screen.tsx.
export default function MealSuggestionsScreen() {
  return (
    <SuggestionScreen<MealSuggestion>
      kind="meal"
      title="Meal Suggestions"
      subtitle="Personalized meal options based on your health information."
      request={requestMealSuggestions}
      card={(meal) => ({ title: meal.name, text: meal.tagline })}
      buttonLabel="View Meal"
      detailsPath="/meal-details"
      icon={{ ios: 'fork.knife', android: 'restaurant', web: 'restaurant' }}
    />
  );
}
