import { Pressable, StyleSheet, Text, View } from 'react-native';

import { AuthButton, authColors, authStyles } from './auth-ui';

export function SetupShell({ section, progress, title, description, children, onBack, onNext, buttonTitle = 'Next  ›' }: { section: string; progress: string; title: string; description: string; children: React.ReactNode; onBack: () => void; onNext: () => void; buttonTitle?: string }) {
  const width = progress === '100% Complete' ? '100%' : `${Number.parseInt(progress, 10)}%`;
  return <View style={[authStyles.screen, styles.screen]}><View style={styles.progress}><Text style={styles.section}>{section}</Text><Text style={styles.progressText}>{progress}</Text></View><View style={styles.track}><View style={[styles.fill, { width }]} /></View><Pressable onPress={onBack}><Text style={styles.back}>‹  Back</Text></Pressable><Text style={styles.title}>{title}</Text><Text style={styles.description}>{description}</Text>{children}<View style={styles.bottom}><AuthButton title={buttonTitle} onPress={onNext} /></View></View>;
}

export function Choice({ title, detail, selected, onPress }: { title: string; detail?: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.choice, selected && styles.selected]}><View style={styles.copy}><Text style={styles.choiceTitle}>{title}</Text>{detail ? <Text style={styles.detail}>{detail}</Text> : null}</View><View style={[styles.radio, selected && styles.radioSelected]}>{selected ? <Text style={styles.check}>✓</Text> : null}</View></Pressable>; }

export const styles = StyleSheet.create({ screen: { padding: 24 }, progress: { flexDirection: 'row', justifyContent: 'space-between' }, section: { color: authColors.green, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, progressText: { color: '#91A4BF', fontSize: 11, fontWeight: '700' }, track: { backgroundColor: '#DDE5EF', borderRadius: 4, height: 6, marginTop: 10 }, fill: { backgroundColor: authColors.green, borderRadius: 4, height: '100%' }, back: { color: '#91A4BF', fontSize: 15, marginTop: 44 }, title: { color: authColors.navy, fontSize: 31, fontWeight: '900', lineHeight: 38, marginTop: 26 }, description: { color: authColors.muted, fontSize: 16, lineHeight: 25, marginTop: 14 }, choice: { alignItems: 'center', backgroundColor: '#FFF', borderColor: '#FFF', borderRadius: 24, borderWidth: 2, flexDirection: 'row', justifyContent: 'space-between', marginTop: 18, minHeight: 84, paddingHorizontal: 20 }, selected: { borderColor: authColors.green }, copy: { flex: 1, gap: 5 }, choiceTitle: { color: authColors.navy, fontSize: 18, fontWeight: '800' }, detail: { color: '#91A4BF', fontSize: 14, lineHeight: 20 }, radio: { alignItems: 'center', borderColor: authColors.border, borderRadius: 14, borderWidth: 2, height: 24, justifyContent: 'center', width: 24 }, radioSelected: { backgroundColor: authColors.green, borderColor: authColors.green }, check: { color: '#FFF', fontWeight: '900' }, bottom: { marginTop: 'auto', paddingTop: 30 } });
